# Generated by Django 5.1.7 on 2025-03-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Disconnected', 'Disconnected'), ('Connected', 'Connected')], default='Disconnected', max_length=50)),
                ('last_communication', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Disconnected', 'Disconnected'), ('Connected', 'Connected'), ('Error', 'Error')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='chargers.charger')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_consumed_kWh', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Active', max_length=50)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chargers.charger')),
            ],
        ),
    ]
