# Generated by Django 5.1.7 on 2025-03-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charger',
            old_name='charger_id',
            new_name='name',
        ),
    ]
