# Generated by Django 5.1.7 on 2025-03-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_rename_charger_id_charger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Charger', 'Charger')], default='Charger', max_length=50),
        ),
    ]
