# Generated by Django 5.1.7 on 2025-03-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0004_charger_box_serial_number_charger_firmware_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='id_tag',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_tag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('FAULTY', 'Faulty')], default='AVAILABLE', max_length=50)),
                ('last_communication', models.DateTimeField(auto_now=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='chargers.charger')),
            ],
        ),
    ]
